### PR TITLE
Adding more VLMs based on Llama 3 Instruct, Gemma 3 Instruct, Mistral v0.2 Instruct, Phi 3 Instruct

### PR DESCRIPTION
**Pull request by RylanSchaeffer**
This is my first pass. Code review would be much appreciated!

### CODE REVIEW

**Comment by siddk** [comment]
High-level question -- how are you importing from the model classes without bumping the base `transformers` version?

**Comment by RylanSchaeffer** [comment]
I didn't even think about that. Can I just bump the version or might that cause foreseeable problems?

**Comment by siddk** [comment]
Hmm -- in general it would be good to test the entire pipeline locally (e.g., run a few dozen steps of training, verify losses go down, etc.) before making a PR.

For this specifically, I'd start by trying to install the latest stable version of `transformers` (does it have Phi-3 and Llama-3) and going from there? 

In the meantime, could you convert this to a draft PR until all the functionality is verified? You can also just close this PR, and maybe individual, smaller PRs for one model at a time.

**Comment by RylanSchaeffer** [comment]
Yeah definitely no problem!

**Pull request closed without merging**
